services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
      - .env
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
